import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const montserrat = localfont({
  src: "../../public/fonts/montserrat-variablefont.woff2",
});

export const metadata: Metadata = {
  title: "Alfa Security",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
